#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("size", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("length_r", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("dataa_address0", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("dataa_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("dataa_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("dataa_d0", 64, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("dataa_q0", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("dataa_address1", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("dataa_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("dataa_q1", 64, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("datac_address0", 7, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("datac_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("datac_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("datac_d0", 64, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("datac_q0", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("datac_address1", 7, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("datac_ce1", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("datac_q1", 64, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("datag_address0", 7, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("datag_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("datag_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("datag_d0", 64, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("datag_q0", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("datag_address1", 7, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("datag_ce1", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("datag_q1", 64, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("datat_address0", 7, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("datat_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("datat_we0", 1, hls_out, 5, "ap_memory", "mem_we", 1),
	Port_Property("datat_d0", 64, hls_out, 5, "ap_memory", "mem_din", 1),
	Port_Property("datat_q0", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("datat_address1", 7, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("datat_ce1", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("datat_q1", 64, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("ap_return", 64, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "compute";
