#pragma line 1 "testproject/test.c" ::: -10
#pragma line 1 "testproject/test.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "testproject/test.c" 2 ::: 184
#pragma line 1 "testproject/fun.h" 1 ::: 185
#pragma line 1 "/usr/include/unistd.h" 1 3 4 ::: 188
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 214
#pragma line 122 "/usr/include/features.h" 3 4 ::: 311
#pragma line 177 "/usr/include/features.h" 3 4 ::: 344
#pragma line 188 "/usr/include/features.h" 3 4 ::: 347
#pragma line 340 "/usr/include/features.h" 3 4 ::: 378
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 382
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 417
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 424
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 447
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 488
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 494
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 512
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 518
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 522
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 538
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 632
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 662
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 686
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 687
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 689
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 691
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 692
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 717
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 728
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 733
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 734
#pragma line 26 "/usr/include/unistd.h" 2 3 4 ::: 735
#pragma line 49 "/usr/include/unistd.h" 3 4 ::: 744
#pragma line 66 "/usr/include/unistd.h" 3 4 ::: 751
#pragma line 99 "/usr/include/unistd.h" 3 4 ::: 775
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix_opt.h" 1 3 4 ::: 883
#pragma line 206 "/usr/include/unistd.h" 2 3 4 ::: 1072
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/environments.h" 1 3 4 ::: 1077
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1100
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1102
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/environments.h" 2 3 4 ::: 1104
#pragma line 210 "/usr/include/unistd.h" 2 3 4 ::: 1143
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1155
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1183
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1185
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1187
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1248
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1255
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1273
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1278
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1289
#pragma line 221 "/usr/include/unistd.h" 2 3 4 ::: 1358
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1368
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1409
#pragma line 230 "/usr/include/unistd.h" 2 3 4 ::: 1412
#pragma line 258 "/usr/include/unistd.h" 3 4 ::: 1430
#pragma line 304 "/usr/include/unistd.h" 3 4 ::: 1464
#pragma line 324 "/usr/include/unistd.h" 3 4 ::: 1474
#pragma line 352 "/usr/include/unistd.h" 3 4 ::: 1489
#pragma line 416 "/usr/include/unistd.h" 3 4 ::: 1527
#pragma line 525 "/usr/include/unistd.h" 3 4 ::: 1627
#pragma line 600 "/usr/include/unistd.h" 3 4 ::: 1692
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/confname.h" 1 3 4 ::: 1706
#pragma line 613 "/usr/include/unistd.h" 2 3 4 ::: 2382
#pragma line 756 "/usr/include/unistd.h" 3 4 ::: 2501
#pragma line 1 "/usr/include/getopt.h" 1 3 4 ::: 2620
#pragma line 51 "/usr/include/getopt.h" 3 4 ::: 2652
#pragma line 122 "/usr/include/getopt.h" 3 4 ::: 2683
#pragma line 188 "/usr/include/getopt.h" 3 4 ::: 2714
#pragma line 874 "/usr/include/unistd.h" 2 3 4 ::: 2716
#pragma line 970 "/usr/include/unistd.h" 3 4 ::: 2802
#pragma line 1016 "/usr/include/unistd.h" 3 4 ::: 2830
#pragma line 1037 "/usr/include/unistd.h" 3 4 ::: 2834
#pragma line 1112 "/usr/include/unistd.h" 3 4 ::: 2882
#pragma line 1140 "/usr/include/unistd.h" 3 4 ::: 2891
#pragma line 1152 "/usr/include/unistd.h" 3 4 ::: 2895
#pragma line 4 "testproject/fun.h" 2 ::: 2906
#pragma line 1 "/usr/include/fcntl.h" 1 3 4 ::: 2907
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 1 3 4 ::: 2943
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 3 4 ::: 2961
#pragma line 60 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 3 4 ::: 2982
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 1 3 4 ::: 2985
#pragma line 120 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3027
#pragma line 154 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3039
#pragma line 166 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3043
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3045
#pragma line 274 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3065
#pragma line 288 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3068
#pragma line 345 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3070
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 2 3 4 ::: 3072
#pragma line 36 "/usr/include/fcntl.h" 2 3 4 ::: 3073
#pragma line 73 "/usr/include/fcntl.h" 3 4 ::: 3089
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3094
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3115
#pragma line 77 "/usr/include/fcntl.h" 2 3 4 ::: 3123
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stat.h" 1 3 4 ::: 3126
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3143
#pragma line 40 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3145
#pragma line 106 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3200
#pragma line 115 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3202
#pragma line 171 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3204
#pragma line 190 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3216
#pragma line 80 "/usr/include/fcntl.h" 2 3 4 ::: 3224
#pragma line 96 "/usr/include/fcntl.h" 3 4 ::: 3225
#pragma line 136 "/usr/include/fcntl.h" 3 4 ::: 3252
#pragma line 172 "/usr/include/fcntl.h" 3 4 ::: 3276
#pragma line 198 "/usr/include/fcntl.h" 3 4 ::: 3289
#pragma line 247 "/usr/include/fcntl.h" 3 4 ::: 3297
#pragma line 267 "/usr/include/fcntl.h" 3 4 ::: 3303
#pragma line 288 "/usr/include/fcntl.h" 3 4 ::: 3310
#pragma line 5 "testproject/fun.h" 2 ::: 3312
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 3313
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 3335
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3336
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3361
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 3364
#pragma line 43 "/usr/include/stdio.h" 3 4 ::: 3365
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 3372
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 3375
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3376
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3408
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3424
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3449
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 3452
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3457
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 3479
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 3500
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 3503
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 3514
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 3524
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 3526
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 3530
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 3579
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 3580
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 3586
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 3588
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 3608
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 3619
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 3660
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 3690
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 3716
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 3720
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 3735
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 3747
#pragma line 109 "/usr/include/stdio.h" 3 4 ::: 3753
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 3758
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 3780
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 3796
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 3813
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 3845
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 3891
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 3905
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 3908
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 3984
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 4023
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 4064
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 4177
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 4240
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 4289
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 4300
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 4330
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 4358
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 4390
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 4402
#pragma line 6 "testproject/fun.h" 2 ::: 4405
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 4406
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4439
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4464
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 4467
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 4477
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 4506
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 4524
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 4525
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 4581
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 4584
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 4706
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 4720
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4741
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4758
#pragma line 75 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4760
#pragma line 104 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4762
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4764
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4773
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4774
#pragma line 58 "/usr/include/time.h" 3 4 ::: 4795
#pragma line 74 "/usr/include/time.h" 3 4 ::: 4798
#pragma line 90 "/usr/include/time.h" 3 4 ::: 4801
#pragma line 102 "/usr/include/time.h" 3 4 ::: 4804
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4807
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4808
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4809
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4834
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4837
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4847
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 4879
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 4916
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 4918
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 4922
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 4925
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4943
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4944
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4946
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 4948
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 4956
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 4974
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4977
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4980
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 4982
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4983
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 4987
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 5018
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5041
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5043
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 5045
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5046
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 5050
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5090
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 5103
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5124
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 5126
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5161
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 5206
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5236
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 5240
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 5258
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 5269
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5271
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 5293
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 5297
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5319
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5321
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 5323
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5324
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5347
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5369
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5446
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5477
#pragma line 276 "/usr/include/stdlib.h" 2 3 4 ::: 5478
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 5621
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 5650
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5675
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5700
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 5703
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 5712
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 5725
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 5732
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 5744
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 5755
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 5801
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 5810
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 5817
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 5823
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 5838
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 5989
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 5991
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 5997
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 5998
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 6016
#pragma line 7 "testproject/fun.h" 2 ::: 6019
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 6020
#pragma line 29 "/usr/include/string.h" 3 4 ::: 6041
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6046
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6071
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 6074
#pragma line 92 "/usr/include/string.h" 3 4 ::: 6111
#pragma line 124 "/usr/include/string.h" 3 4 ::: 6114
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 6151
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 6194
#pragma line 207 "/usr/include/string.h" 3 4 ::: 6216
#pragma line 231 "/usr/include/string.h" 3 4 ::: 6218
#pragma line 258 "/usr/include/string.h" 3 4 ::: 6223
#pragma line 278 "/usr/include/string.h" 3 4 ::: 6226
#pragma line 310 "/usr/include/string.h" 3 4 ::: 6236
#pragma line 337 "/usr/include/string.h" 3 4 ::: 6241
#pragma line 393 "/usr/include/string.h" 3 4 ::: 6262
#pragma line 439 "/usr/include/string.h" 3 4 ::: 6293
#pragma line 484 "/usr/include/string.h" 3 4 ::: 6316
#pragma line 512 "/usr/include/string.h" 3 4 ::: 6322
#pragma line 550 "/usr/include/string.h" 3 4 ::: 6346
#pragma line 8 "testproject/fun.h" 2 ::: 6372
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 6373
#pragma line 34 "/usr/include/time.h" 3 4 ::: 6394
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6399
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6424
#pragma line 38 "/usr/include/time.h" 2 3 4 ::: 6427
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 6432
#pragma line 42 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 6454
#pragma line 60 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 6461
#pragma line 42 "/usr/include/time.h" 2 3 4 ::: 6486
#pragma line 132 "/usr/include/time.h" 3 4 ::: 6489
#pragma line 187 "/usr/include/time.h" 3 4 ::: 6527
#pragma line 219 "/usr/include/time.h" 3 4 ::: 6549
#pragma line 237 "/usr/include/time.h" 3 4 ::: 6558
#pragma line 9 "testproject/fun.h" 2 ::: 6703
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 6704
#pragma line 30 "/usr/include/math.h" 3 4 ::: 6726
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 6729
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 6755
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 6787
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 6788
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 6793
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 6818
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 6820
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 6845
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 6846
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 6865
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 6869
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 6893
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 6897
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 6922
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 6927
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 6944
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 6950
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 6957
#pragma line 83 "/usr/include/math.h" 3 4 ::: 6963
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 6964
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7041
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7071
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7240
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7311
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 7314
#pragma line 93 "/usr/include/math.h" 3 4 ::: 7315
#pragma line 104 "/usr/include/math.h" 3 4 ::: 7318
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 7319
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7396
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7426
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7595
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7666
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 7669
#pragma line 139 "/usr/include/math.h" 3 4 ::: 7670
#pragma line 151 "/usr/include/math.h" 3 4 ::: 7673
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 7674
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7751
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7781
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7950
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 8021
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 8024
#pragma line 167 "/usr/include/math.h" 3 4 ::: 8025
#pragma line 248 "/usr/include/math.h" 3 4 ::: 8092
#pragma line 268 "/usr/include/math.h" 3 4 ::: 8094
#pragma line 282 "/usr/include/math.h" 3 4 ::: 8096
#pragma line 304 "/usr/include/math.h" 3 4 ::: 8106
#pragma line 318 "/usr/include/math.h" 3 4 ::: 8108
#pragma line 346 "/usr/include/math.h" 3 4 ::: 8116
#pragma line 411 "/usr/include/math.h" 3 4 ::: 8170
#pragma line 428 "/usr/include/math.h" 3 4 ::: 8172
#pragma line 448 "/usr/include/math.h" 3 4 ::: 8176
#pragma line 470 "/usr/include/math.h" 3 4 ::: 8191
#pragma line 10 "testproject/fun.h" 2 ::: 8247
#pragma line 2 "testproject/test.c" 2 ::: 8413
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 8421
#pragma line 43 "/usr/include/assert.h" 3 4 ::: 8442
#pragma line 68 "/usr/include/assert.h" 3 4 ::: 8447
#pragma line 100 "/usr/include/assert.h" 3 4 ::: 8463
#pragma line 10 "testproject/test.c" 2 ::: 8469
