#pragma line 1 "testproject/test.c" ::: 0
#pragma line 1 "testproject/test.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/home/rika/Vivado_HLS/2016.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "testproject/test.c" 2 ::: 194
#pragma line 1 "testproject/fun.h" 1 ::: 195
#pragma line 1 "/usr/include/unistd.h" 1 3 4 ::: 198
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 224
#pragma line 122 "/usr/include/features.h" 3 4 ::: 321
#pragma line 177 "/usr/include/features.h" 3 4 ::: 354
#pragma line 188 "/usr/include/features.h" 3 4 ::: 357
#pragma line 340 "/usr/include/features.h" 3 4 ::: 388
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 392
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 427
#pragma line 343 "/usr/include/features.h" 2 3 4 ::: 434
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 457
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 498
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 504
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 522
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 532
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 534
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 538
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 548
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 601
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 642
#pragma line 351 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 672
#pragma line 415 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 696
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 697
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 699
#pragma line 416 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 701
#pragma line 365 "/usr/include/features.h" 2 3 4 ::: 702
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 727
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 738
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 743
#pragma line 389 "/usr/include/features.h" 2 3 4 ::: 744
#pragma line 26 "/usr/include/unistd.h" 2 3 4 ::: 745
#pragma line 49 "/usr/include/unistd.h" 3 4 ::: 754
#pragma line 66 "/usr/include/unistd.h" 3 4 ::: 761
#pragma line 99 "/usr/include/unistd.h" 3 4 ::: 785
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix_opt.h" 1 3 4 ::: 893
#pragma line 206 "/usr/include/unistd.h" 2 3 4 ::: 1082
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/environments.h" 1 3 4 ::: 1087
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1110
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1112
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/environments.h" 2 3 4 ::: 1114
#pragma line 210 "/usr/include/unistd.h" 2 3 4 ::: 1153
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1165
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1193
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1195
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1197
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1258
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1265
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1283
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1288
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1299
#pragma line 221 "/usr/include/unistd.h" 2 3 4 ::: 1368
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1378
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1419
#pragma line 230 "/usr/include/unistd.h" 2 3 4 ::: 1422
#pragma line 258 "/usr/include/unistd.h" 3 4 ::: 1440
#pragma line 304 "/usr/include/unistd.h" 3 4 ::: 1474
#pragma line 324 "/usr/include/unistd.h" 3 4 ::: 1484
#pragma line 352 "/usr/include/unistd.h" 3 4 ::: 1499
#pragma line 416 "/usr/include/unistd.h" 3 4 ::: 1537
#pragma line 525 "/usr/include/unistd.h" 3 4 ::: 1637
#pragma line 600 "/usr/include/unistd.h" 3 4 ::: 1702
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/confname.h" 1 3 4 ::: 1716
#pragma line 613 "/usr/include/unistd.h" 2 3 4 ::: 2392
#pragma line 756 "/usr/include/unistd.h" 3 4 ::: 2511
#pragma line 1 "/usr/include/getopt.h" 1 3 4 ::: 2630
#pragma line 51 "/usr/include/getopt.h" 3 4 ::: 2662
#pragma line 122 "/usr/include/getopt.h" 3 4 ::: 2693
#pragma line 188 "/usr/include/getopt.h" 3 4 ::: 2724
#pragma line 874 "/usr/include/unistd.h" 2 3 4 ::: 2726
#pragma line 970 "/usr/include/unistd.h" 3 4 ::: 2812
#pragma line 1016 "/usr/include/unistd.h" 3 4 ::: 2840
#pragma line 1037 "/usr/include/unistd.h" 3 4 ::: 2844
#pragma line 1112 "/usr/include/unistd.h" 3 4 ::: 2892
#pragma line 1140 "/usr/include/unistd.h" 3 4 ::: 2901
#pragma line 1152 "/usr/include/unistd.h" 3 4 ::: 2905
#pragma line 4 "testproject/fun.h" 2 ::: 2916
#pragma line 1 "/usr/include/fcntl.h" 1 3 4 ::: 2917
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 1 3 4 ::: 2953
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 3 4 ::: 2971
#pragma line 60 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 3 4 ::: 2992
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 1 3 4 ::: 2995
#pragma line 120 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3037
#pragma line 154 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3049
#pragma line 166 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3053
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3055
#pragma line 274 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3075
#pragma line 288 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3078
#pragma line 345 "/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h" 3 4 ::: 3080
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/fcntl.h" 2 3 4 ::: 3082
#pragma line 36 "/usr/include/fcntl.h" 2 3 4 ::: 3083
#pragma line 73 "/usr/include/fcntl.h" 3 4 ::: 3099
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3104
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3125
#pragma line 77 "/usr/include/fcntl.h" 2 3 4 ::: 3133
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stat.h" 1 3 4 ::: 3136
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3153
#pragma line 40 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3155
#pragma line 106 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3210
#pragma line 115 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3212
#pragma line 171 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3214
#pragma line 190 "/usr/include/x86_64-linux-gnu/bits/stat.h" 3 4 ::: 3226
#pragma line 80 "/usr/include/fcntl.h" 2 3 4 ::: 3234
#pragma line 96 "/usr/include/fcntl.h" 3 4 ::: 3235
#pragma line 136 "/usr/include/fcntl.h" 3 4 ::: 3262
#pragma line 172 "/usr/include/fcntl.h" 3 4 ::: 3286
#pragma line 198 "/usr/include/fcntl.h" 3 4 ::: 3299
#pragma line 247 "/usr/include/fcntl.h" 3 4 ::: 3307
#pragma line 267 "/usr/include/fcntl.h" 3 4 ::: 3313
#pragma line 288 "/usr/include/fcntl.h" 3 4 ::: 3320
#pragma line 5 "testproject/fun.h" 2 ::: 3322
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 3323
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 3345
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3346
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3371
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 3374
#pragma line 43 "/usr/include/stdio.h" 3 4 ::: 3375
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 3382
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 3385
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 3386
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 3418
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3434
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3459
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 3462
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 3467
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 3489
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 3510
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 3513
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 3524
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 3534
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 3536
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 3540
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 3589
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 3590
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 3596
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 3598
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 3618
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 3629
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 3670
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 3700
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 3726
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 3730
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 3745
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 3757
#pragma line 109 "/usr/include/stdio.h" 3 4 ::: 3763
#pragma line 121 "/usr/include/stdio.h" 3 4 ::: 3768
#pragma line 152 "/usr/include/stdio.h" 3 4 ::: 3790
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 3806
#pragma line 167 "/usr/include/stdio.h" 2 3 4 ::: 3823
#pragma line 210 "/usr/include/stdio.h" 3 4 ::: 3855
#pragma line 270 "/usr/include/stdio.h" 3 4 ::: 3901
#pragma line 307 "/usr/include/stdio.h" 3 4 ::: 3915
#pragma line 320 "/usr/include/stdio.h" 3 4 ::: 3918
#pragma line 413 "/usr/include/stdio.h" 3 4 ::: 3994
#pragma line 469 "/usr/include/stdio.h" 3 4 ::: 4033
#pragma line 529 "/usr/include/stdio.h" 3 4 ::: 4074
#pragma line 657 "/usr/include/stdio.h" 3 4 ::: 4187
#pragma line 733 "/usr/include/stdio.h" 3 4 ::: 4250
#pragma line 796 "/usr/include/stdio.h" 3 4 ::: 4299
#pragma line 827 "/usr/include/stdio.h" 3 4 ::: 4310
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 4340
#pragma line 856 "/usr/include/stdio.h" 2 3 4 ::: 4368
#pragma line 911 "/usr/include/stdio.h" 3 4 ::: 4400
#pragma line 932 "/usr/include/stdio.h" 3 4 ::: 4412
#pragma line 6 "testproject/fun.h" 2 ::: 4415
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 4416
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4449
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4474
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 4477
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 4487
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 4516
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 4534
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 4535
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 4591
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 4594
#pragma line 263 "/usr/include/stdlib.h" 3 4 ::: 4716
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 4730
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4751
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4768
#pragma line 75 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4770
#pragma line 104 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4772
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4774
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4783
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4784
#pragma line 58 "/usr/include/time.h" 3 4 ::: 4805
#pragma line 74 "/usr/include/time.h" 3 4 ::: 4808
#pragma line 90 "/usr/include/time.h" 3 4 ::: 4811
#pragma line 102 "/usr/include/time.h" 3 4 ::: 4814
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4817
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4818
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4819
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4844
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4847
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 4857
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 4889
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 4926
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 4928
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 4932
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 4935
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4953
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 4954
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 4956
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 4958
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 4966
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 4984
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4987
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 4990
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 4992
#pragma line 217 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 4993
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 4997
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 5028
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5051
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5053
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 5055
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5056
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 5060
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5100
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 5113
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5134
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 5136
#pragma line 48 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 5171
#pragma line 100 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 5216
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5246
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 5250
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 5268
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 5279
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5281
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 5303
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 5307
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5329
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5331
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 5333
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5334
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5357
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5379
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 5456
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 5487
#pragma line 276 "/usr/include/stdlib.h" 2 3 4 ::: 5488
#pragma line 426 "/usr/include/stdlib.h" 3 4 ::: 5631
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 5660
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5685
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5710
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 5713
#pragma line 454 "/usr/include/stdlib.h" 2 3 4 ::: 5722
#pragma line 475 "/usr/include/stdlib.h" 3 4 ::: 5735
#pragma line 494 "/usr/include/stdlib.h" 3 4 ::: 5742
#pragma line 516 "/usr/include/stdlib.h" 3 4 ::: 5754
#pragma line 536 "/usr/include/stdlib.h" 3 4 ::: 5765
#pragma line 595 "/usr/include/stdlib.h" 3 4 ::: 5811
#pragma line 618 "/usr/include/stdlib.h" 3 4 ::: 5820
#pragma line 673 "/usr/include/stdlib.h" 3 4 ::: 5827
#pragma line 689 "/usr/include/stdlib.h" 3 4 ::: 5833
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 5848
#pragma line 872 "/usr/include/stdlib.h" 3 4 ::: 5999
#pragma line 908 "/usr/include/stdlib.h" 3 4 ::: 6001
#pragma line 921 "/usr/include/stdlib.h" 3 4 ::: 6007
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 6008
#pragma line 922 "/usr/include/stdlib.h" 2 3 4 ::: 6026
#pragma line 7 "testproject/fun.h" 2 ::: 6029
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 6030
#pragma line 29 "/usr/include/string.h" 3 4 ::: 6051
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6056
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6081
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 6084
#pragma line 92 "/usr/include/string.h" 3 4 ::: 6121
#pragma line 124 "/usr/include/string.h" 3 4 ::: 6124
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 6161
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 6204
#pragma line 207 "/usr/include/string.h" 3 4 ::: 6226
#pragma line 231 "/usr/include/string.h" 3 4 ::: 6228
#pragma line 258 "/usr/include/string.h" 3 4 ::: 6233
#pragma line 278 "/usr/include/string.h" 3 4 ::: 6236
#pragma line 310 "/usr/include/string.h" 3 4 ::: 6246
#pragma line 337 "/usr/include/string.h" 3 4 ::: 6251
#pragma line 393 "/usr/include/string.h" 3 4 ::: 6272
#pragma line 439 "/usr/include/string.h" 3 4 ::: 6303
#pragma line 484 "/usr/include/string.h" 3 4 ::: 6326
#pragma line 512 "/usr/include/string.h" 3 4 ::: 6332
#pragma line 550 "/usr/include/string.h" 3 4 ::: 6356
#pragma line 8 "testproject/fun.h" 2 ::: 6382
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 6383
#pragma line 34 "/usr/include/time.h" 3 4 ::: 6404
#pragma line 1 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6409
#pragma line 56 "/home/rika/Vivado_HLS/2016.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6434
#pragma line 38 "/usr/include/time.h" 2 3 4 ::: 6437
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 6442
#pragma line 42 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 6464
#pragma line 60 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 6471
#pragma line 42 "/usr/include/time.h" 2 3 4 ::: 6496
#pragma line 132 "/usr/include/time.h" 3 4 ::: 6499
#pragma line 187 "/usr/include/time.h" 3 4 ::: 6537
#pragma line 219 "/usr/include/time.h" 3 4 ::: 6559
#pragma line 237 "/usr/include/time.h" 3 4 ::: 6568
#pragma line 9 "testproject/fun.h" 2 ::: 6713
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 6714
#pragma line 30 "/usr/include/math.h" 3 4 ::: 6736
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 6739
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 6765
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 6797
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 6798
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 6803
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 6828
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 6830
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 6855
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 6856
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 6875
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 6879
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 6903
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 6907
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 6932
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 6937
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 6954
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 6960
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 6967
#pragma line 83 "/usr/include/math.h" 3 4 ::: 6973
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 6974
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7051
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7081
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7250
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7321
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 7324
#pragma line 93 "/usr/include/math.h" 3 4 ::: 7325
#pragma line 104 "/usr/include/math.h" 3 4 ::: 7328
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 7329
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7406
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7436
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7605
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7676
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 7679
#pragma line 139 "/usr/include/math.h" 3 4 ::: 7680
#pragma line 151 "/usr/include/math.h" 3 4 ::: 7683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 7684
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7761
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7791
#pragma line 304 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 7960
#pragma line 389 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 8031
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 8034
#pragma line 167 "/usr/include/math.h" 3 4 ::: 8035
#pragma line 248 "/usr/include/math.h" 3 4 ::: 8102
#pragma line 268 "/usr/include/math.h" 3 4 ::: 8104
#pragma line 282 "/usr/include/math.h" 3 4 ::: 8106
#pragma line 304 "/usr/include/math.h" 3 4 ::: 8116
#pragma line 318 "/usr/include/math.h" 3 4 ::: 8118
#pragma line 346 "/usr/include/math.h" 3 4 ::: 8126
#pragma line 411 "/usr/include/math.h" 3 4 ::: 8180
#pragma line 428 "/usr/include/math.h" 3 4 ::: 8182
#pragma line 448 "/usr/include/math.h" 3 4 ::: 8186
#pragma line 470 "/usr/include/math.h" 3 4 ::: 8201
#pragma line 10 "testproject/fun.h" 2 ::: 8257
#pragma line 2 "testproject/test.c" 2 ::: 8423
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 8431
#pragma line 43 "/usr/include/assert.h" 3 4 ::: 8452
#pragma line 68 "/usr/include/assert.h" 3 4 ::: 8457
#pragma line 100 "/usr/include/assert.h" 3 4 ::: 8473
#pragma line 10 "testproject/test.c" 2 ::: 8479
